spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/agenda?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jbdc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialet: org.hibernate.dialet.MySQL5Dialet